### ISSUE TITLE
Problem with the declaration of a SocketIOStatic variable

### ISSUE THREAD

**Issue by valentin4ahif** [rstropek-teaching/real-time-game-quiz-4ahif-valentin4ahif#1]
I have this two lines of code in my client.ts file:
```
declare const io: SocketIOStatic;
const socket = io();
```
But when I run the file, I get an "_ReferenceError: io is not defined_" and I don't know why, because I 
 did some research on the internet and at your teaching material and I could not find any difference.
Probably I need a line which initialises "io" or something?

So my question now is, why doesn't this work and how can I solve this problem? Thank you.

**Comment by rstropek** [comment]
@valentin4ahif Hmm, maybe you have forgotten to include socket.io in your HTML-file: `<script src="/socket.io/socket.io.js"></script>` (see [this slide](https://rstropek.github.io/htl-mobile-computing/#/9/9) in the course material)? This is the only reason I could think of given your error message.

If this does not solve your problem, please check in your source code. I can take a look at it and give additional feedback.

Greetings,
Rainer Stropek.
